version: 2.1

jobs:
  prepare:
    docker:
      - image: finalgene/composer

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Validating composer file
          command: composer validate --no-check-all --no-check-publish

      - run:
          name: Installing dependencies
          command: composer install --no-interaction

      - run:
          name: Installing tools
          command: composer bin all install --no-interaction

      - persist_to_workspace:
          root: ~/project
          paths:
            - vendor
            - tools/codacy/vendor/
            - tools/phpstan/vendor/
            - tools/phpunit/vendor/
            - tools/squizlabs/vendor/

  analysis:
    docker:
      - image: finalgene/php-cli:7.2

    working_directory: ~/project

    steps:
      - checkout

      - attach_workspace:
          at: ~/project

      - run:
          name: Anlaysing code
          command: vendor/bin/phpstan analyze src tests

  style-check:
    docker:
      - image: finalgene/php-cli:7.2

    working_directory: ~/project

    steps:
      - checkout

      - attach_workspace:
          at: ~/project

      - run:
          name: Checking code style
          command: vendor/bin/phpcs -p

  phpunit:
    docker:
      - image: finalgene/php-cli:7.2-xdebug

    working_directory: ~/project

    steps:
      - checkout

      - attach_workspace:
          at: ~/project

      - run:
          name: Executing unit tests
          command: |
            php -d zend_extension=xdebug.so vendor/bin/phpunit \
              --coverage-text \
              --coverage-clover=build/logs/coverage.clover.xml \
              --log-junit=.build/test-results/phpunit/results.xml
      - run:
          name: Uploading coverage data
          command: vendor/bin/codacycoverage clover build/logs/coverage.clover.xml

      - store_test_results:
          path: .build/test-results

workflows:
  analyse-test:
    jobs:
      - prepare

      - analysis:
          requires:
            - prepare

      - style-check:
          requires:
            - prepare

      - phpunit:
          requires:
            - prepare
